server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-course
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/digitalhouse-dev
    username: usr-digitalhouse
    password: pwd-digitalhouse
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

info:
  application:
    name: api-course

eureka:
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/